#!/bin/bash
. util.sh 
LOG_ROOT=${LOG_ROOT:-/var/log/ezstreamer}
exec 2> ${LOG_ROOT}/playlist.err

stream=${1:-radio}

[ -n "$stream" ] && {
   kill -SIGUSR1 $(cat /tmp/pids/${stream}.pid)
} || { echo "A stream name is required"; exit 1; }
